---
splunk:
  conf:
    - key: web
      value:
        directory: /opt/splunk/etc/system/local
        content:
          settings:
            tools.proxy.on: true
            tools.proxy.base: http://localhost:8888
